### ISSUE TITLE
outTanCtrl not found in maya cmds.

### ISSUE THREAD

**Issue by kmarcinowski** [blurstudio/TwistSpline#18]
Hello,
I've compiled .mll for Maya 2018 but can not build the rig using"twistSplineBuilder.py".
There is no such function in maya cmds as "outTanCtrl" <- which seems correct at least with default one.
Could you please advise me a bit on how I should proceed with that?

`# Error: AttributeError: file <maya console> line 138: 'module' object has no attribute 'outTanCtrl' #`
Line 138:
`	outTanCtrl = cmds.outTanCtrl(radius=v, constructionHistory=False)[0]`

Thank you in advance,
Krzysztof

**Comment by tbttfox** [comment]
Ah, that just looks like a find/replace gone bad. 
I can't actually test this fix right now, but that line should probably be:
`outTanCtrl = cmds.circle(radius=v, constructionHistory=False)[0]`

**Comment by kmarcinowski** [comment]
Thank you ;) That was it!

**Comment by tbttfox** [comment]
Ok, committed a fix to this (among other things)
