### ISSUE TITLE
[Bug]: Spline twist reversed and inversed scale on twist controls with the new twistMultiTangent node

### ISSUE THREAD

**Issue by mdilena** [blurstudio/TwistSpline#32]
### Summary

It seems like the twisting of the spline is reversed with the new node, as rotating the twist control in one direction will rotate the joints in the opposite. As an addition, the twist controls get an inversed scale from the node `twistMat` output, when the rig is scaled up.

### Expected Behavior

When rotating one of the twist control clockwise, the riders/joints should rotate clockwise as well.

### Steps to Reproduce Behavior

Use the spline builder script to build an example spline, then rotate any of the twist controls to see the behaviour, after turning on the `useTwist` attribute.
For the scale, try scaling the rig from the global control and the twist control will become tinier the more it scales.

### Solution

There is a way to solve this with Maya nodes, in order to multiply the control's rotateX value by -1 and remove the scale from the output twist matrix with a pick matrix, but it would be nice to solve it within the node's code if it's possible.

### Environment

- Version: 1.2.0
- OS: Linux Rocky 8

### Additional Context

A video showing the issues: https://youtu.be/8EAc69T-Xxc

**Comment by tbttfox** [comment]
OH ... right. I guess I forgot to add something to the builder script.
The old setup built the twist matrix with one inverted axis, and thus the twist values were the opposite of what they should be. A positive twist of the CV controller was equivalent to a negative twist on the twist control.
I added a plug to the spline called `twistMultiplier`.  It defaults to the old, incorrect behavior (-1.0) with a "flipped" twist.  Set that to 1.0 to get the correct twist behavior (I forgot to put that into the builder).  I'm planning on doing a "deprecation" and eventually having that plug default to 1.0, but that's a long-term thing.

As for the scaling twist matrices: I do all the math in worldspace with normalized vectors, then put that back into spline-space.
The old setup had this problem too, but it used a decompose matrix to get just the rotations.
I'm using the offsetParentMatrix in the new setup so it's inheriting this "worldspace normalized scale" you're seeing as an inverse.
So you can disconnect and clear out the .opm from the twist hbfr. Then connect the twist matrix to the rotation through a decompose matrix for a quick-fix.
But yeah, the real fix is for me to get the scale of the CV and include that in the twist matrix.

**Comment by mdilena** [comment]
Sorry, didn't notice the new multiplier plug, will definitely use that! And no worries about the scale for now, I remember it was like that in the old script as well, I can compensate for it as you mentioned for the time being 👍

**Comment by tbttfox** [comment]
Should be fixed by #33
