### ISSUE TITLE
[Bug]: Memory Leak Issue

### ISSUE THREAD

**Issue by dewclawpaww** [blurstudio/TwistSpline#38]
### Summary

I am using the twistSpline in a lot of components I didn't notice it during small tests or smaller components but since the spline is so stable I was building more complex things with it and the memory leaks piled up and froze up maya. If you run animation moving the spline around you can open up your task manager and see the memory start to slowly pile up. Run it with a lot of riders and you'll see it pile up faster.

I am on Windows, compiled with VS and on maya 2024.

### Expected Behavior

The memory should not be piling up at all, a tiny amount is fine but it every other circumstance with most plug ins I've built and compiled I don't see the memory move at all.

### Steps to Reproduce Behavior

I'm trying to run the profiler in VS but I'm unable to get it to work on my end.

### Solution

I would heavily suggest running a profiler on the plugin and try finding out where the leaky bits are coming from but I'm not sure what to suggest.

### Environment

-Maya 2024.2 - Visual Studio 2022 Version 17.9.3

### Additional Context

I can provide video proof if needed but reach out to me if you want me to sit down and replicate the issue with you.

**Comment by dewclawpaww** [comment]
I found some suspicious code after many many hours of checking with visual studio debugger

in twistSplineData.cpp

`void TwistSplineData::copy(const MPxData& other) {
    if (other.typeId() == TwistSplineData::id) {
        const TwistSplineData* otherData = (const TwistSplineData*) & other;
        const TwistSplineT * x = otherData->getSpline();
        _twistSpline = new TwistSplineT(*x);
    }
    else {
        //  we need to convert to the other type based on its iff Tag
        cerr << "wrong data format!" << endl;
    }
    return;
}`

I changed it to this

`void TwistSplineData::copy(const MPxData& other) {
    if (other.typeId() == TwistSplineData::id) {
        const TwistSplineData* otherData = (const TwistSplineData*)&other;
        const TwistSplineT* x = otherData->getSpline();
        delete _twistSpline;  // Free the old data
        _twistSpline = new TwistSplineT(*x);
    }
    else {
        cerr << "wrong data format!" << endl;
    }
}`

I will do more testing but the memory leak error stop sputtering a report after that.

**Comment by dewclawpaww** [comment]
I just compiled it as release cleaned up and I no longer have any issues. So this may be a potential fix for now but I would explore it further as there may be smaller leaks I missed.

**Comment by tbttfox** [comment]
Fixed by https://github.com/blurstudio/TwistSpline/pull/39

I'm keeping an eye on it, but if it's not actually fixed feel free to poke me again. Hopefully it'll take me less than a month to get back to you.
